### ISSUE TITLE
Width at starting.

### ISSUE THREAD

**Issue by Koromilo** [alexkdeveloper/radio#19]
Hello!
Just installed the flatpak. I see this issue that disturbs me a little. 
When the app starts, it is wide taking all the width of the screen, but only 1/4 of the vertical space.
I would like to control the size in the settings, or something like this.
Sorry, I am not really a coder but I can modify a config file if you point me to it.
Thanks!

**Comment by alexkdeveloper** [comment]
Hi.

This behavior may be caused by some names and addresses of stations downloaded from the server. 

Try disabling station downloads at startup in the app settings.
