### ISSUE TITLE
Panel spills over right side

### ISSUE THREAD

**Issue by CaptainMorgan12** [alexkdeveloper/radio#22]
Environment: mobile phone librem5, 720x1440, wayland, radio flatpak 1.0.13, Pureos 10.

![goodvibes](https://github.com/alexkdeveloper/radio/assets/80182265/864894a2-86cd-4faf-bd54-c6dc702ccd5f)

**Comment by alexkdeveloper** [comment]
The buttons for adding and removing stations were moved to the menu in version 1.0.14

**Comment by CaptainMorgan12** [comment]
Awesome thank you alex that fixed the issue and all buttons in the menu now align with screen width!
