### ISSUE TITLE
Search Start with Enter

### ISSUE THREAD

**Issue by BenOoi** [alexkdeveloper/radio#7]
When you open the search bar type in the word and press enter, nothing happens. The only way to start a search is clicking the search icon on the right.

I expected enter to initiate a search.

**Comment by alexkdeveloper** [comment]
I'm using an EventControllerKey, and at the moment I can't bind any event to this key to make it happen. I will try to solve this problem in the next releases of the application.

**Comment by alexkdeveloper** [comment]
I tried to do something, but...
pressing the enter key for some reason triggers the desired event only when the search field is out of focus. When the search field is in focus, nothing happens. Strange behavior.
And for the user, they just need the search field to be in focus. I will try to solve this issue somehow.
Do you have any ideas?
